name: Vitest Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  vitest-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout qualibrate repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Use Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Step 3: Cache frontend dependencies
      - uses: actions/cache@v4
        id: frontend-cache-id
        with:
          path: src/frontend/node_modules
          key: npm-${{ hashFiles('src/frontend/**/package-lock.json') }}
          restore-keys: npm-

      # Step 4: Install frontend dependencies
      - name: Install npm dependencies
        if: steps.frontend-cache-id.outputs.cache-hit != 'true'
        working-directory: src/frontend
        run: npm ci

      # Step 5: Run Vitest unit tests
      - name: Run Vitest Tests
        working-directory: src/frontend
        run: npm test